### ISSUE TITLE
Stresses Input data required ?

### ISSUE THREAD

**Issue by yvanblanchard** [zhangty019/S3_DeformFDM#7]
Hello,

I would like to know which inputs are necessary ?
- I understand that a test mesh must be generated (and not a surfac triangle mesh as STL) ?
- Do I really need the principal stresses field data (texte file) ? Even if I don't want to slice by taking structurak strength into account (only optimization of support structures and quality finish) ?

thank you

**Comment by moorjuli** [comment]
Hey,
I am not the author of this, but maybe I can help you, since at the moment I am trying to figure this project out as well. If you do not want to take the structural strength part into account, you don't need the data file, as far as I know. 
My workflow on creating the .tet file if you don't need FEA Analysis, is first using [TetGen](https://wias-berlin.de/software/tetgen/) to create a .mesh and then use [Mouette](https://github.com/GCoiffier/mouette/) to convert it to .tet format. 
Before opening the file with the software, you also need to modify the _updateFrameworkParameter() function in the MainWindow.cpp and add your file there, or otherwise no option will appear for your model in the software. The Parameters there are not documented very well, so try copying it from one of the other models set there.

**Comment by zhangty019** [comment]
Hi @yvanblanchard, the stress file is generated by FEA software, if we don't need the SR (strength reinforcement), there is no need to input the stress field.

@moorjuli Thanks for your kind reply and help.

**Comment by yvanblanchard** [comment]
Great. Thank both of you !
